### ISSUE TITLE
NullReferenceException with various other mods

### ISSUE THREAD

**Issue by DerpyFirework** [KSP-TaxiService/CommNetConstellation#1]
Using this with ModularFlightItegrator and PersitentDynamicPodNames causes the log to be spammed with NullRefs. output_log.txt attached.

Mods:
-[ModuleManager](http://forum.kerbalspaceprogram.com/index.php?/topic/50533-121-module-manager-275-november-29th-2016-better-late-than-never/) 2.7.5
-[ModularFlightItegrator](http://forum.kerbalspaceprogram.com/index.php?/topic/106369-12-modularflightintegrator-123-december-11th/) 1.2.3.0
-[PersistentDynamicPodNames](http://forum.kerbalspaceprogram.com/index.php?/topic/142900-12-persistent-dynamic-pod-names-release/) 0.1.6.1
-CommNetConstellation 0.4

KSP version 1.2.2.1622 Windows 64-bit
[output_log.txt](https://github.com/KSP-TaxiService/CommNetConstellation/files/846158/output_log.txt)

**Comment by DerpyFirework** [comment]
After another quick test, it seems it's not just this combination of mods. Will try to hunt down all the mods from my list that cause this error

**Comment by KSP-TaxiService** [comment]
Thanks so much for the detailed report. Those two mods are sufficient for me to verify this NullReferenceException spam.

It seems the CommNode of a vessel is somehow modified by one or both of other mods enough to cause the equal comparison to fail. I may need to shift away from the object comparison towards unique IDs of a vessel/CommNode.
