### ISSUE TITLE
Commnet behaves like vanilla when joining a DMP server for the second time.

### ISSUE THREAD

**Issue by FrostBird347** [KSP-TaxiService/CommNetConstellation#13]
After joining a dmp server for the second time, the commnet connections behave as if the mod is not installed. The commnet menu still shows up, but all the ships behave like in vanilla (they all connect to each other). I discovered that removing the commnet scenario file in the server before the player rejoins fixes the issue for one session, but it also removes all the existing channels.
On first join:
![First Join](https://user-images.githubusercontent.com/39435218/66014482-ace61a80-e501-11e9-9744-18d4ff0310a3.png)
On second join:
![Second Join](https://user-images.githubusercontent.com/39435218/66014537-df901300-e501-11e9-8a8e-534ecd24fffe.png)
Reconnecting after removing the commnet scenarios:
![Reconnect bad fix](https://user-images.githubusercontent.com/39435218/66014701-67761d00-e502-11e9-8d98-7eb972ea10eb.png)

I have checked the logs, but I could not see any error messages in both the dmp server log or ksp's logs. I also checked the save files of a single player world and compared the commnet section in the save file to the scenario file, but it appeared to be the same.

**Comment by KSP-TaxiService** [comment]
Hi, 

Based on my server session of DMP and CNC, the stock CommNet logic is started instead when DMP rejoins for subsequent times.

I am trying to find out why the game is ignoring the CNC instructions to remove the stock logic and start CNC logic.

**Comment by KSP-TaxiService** [comment]
Hi @FrostBird347,

Kindly assist to download and replace [CommNetConstellation_Build.zip](https://github.com/KSP-TaxiService/CommNetConstellation/files/3698289/CommNetConstellation_Build.zip) on your side. It should be able to kill the stock CommNet logic when you rejoin in DMP.

Thanks.

**Comment by FrostBird347** [comment]
Thanks, 
I have downloaded and the mod and tested it. Everything appears to be working normally, I have tried restarting the server, disconnecting the client and restarting ksp. The only bug I noticed was that when I first connected, it was not saving the ground station's frequencies, but after restarting the game it was working and I did not notice that bug after, even after removing and reinstalling dmp.

**Comment by KSP-TaxiService** [comment]
Hi, thanks for your confirmation!

For your information, CNC data like ground station frequencies are stored in cnc scenario of persistent.sfs. Thus, if you disconnect DMP without exiting to Main Menu first, the updated CNC scenario will not be sent to DMP server for saving.
