### ISSUE TITLE
The last couple releases all got en empty folder named KSPDLL_1_8_1 or alike

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-TaxiService/CommNetConstellation#16]
GameData\CommNetConstellation\Plugins\KSPDLL_1_8_1\

empty folder, actually in 1.5-89-develop

**Comment by KSP-TaxiService** [comment]
Yes, there isn't any change to the auto-build script for that folder. It is some stuff downloaded for compilation.

My guess is the folder is accidental leftover in the build environment after the first attempt against the new Unity Engine.

For now, it is harmless bit.
