### ISSUE TITLE
Probe control with no connection

### ISSUE THREAD

**Issue by FrostBird347** [KSP-TaxiService/CommNetConstellation#17]
I noticed that my station on a DMP server would still be controllable when there is no signal or kerbals on board.
![ksp2](https://user-images.githubusercontent.com/39435218/70302601-76e25100-1838-11ea-9217-ba260a3e5735.png)
![ksp1](https://user-images.githubusercontent.com/39435218/70302587-6d58e900-1838-11ea-8681-ab0595515446.png)

In the settings I have it set to require a connection to allow probe control.

**Comment by FrostBird347** [comment]
Restarted the game and...
![ksp3](https://user-images.githubusercontent.com/39435218/70303028-857d3800-1839-11ea-842d-12d49f8d0cfa.png)
It stayed connected until I switched from the tracking station to the ship, but I could still control it.

Although I can control probes that are not connected, probes without power can not be controlled, so I know that it has something to do with the connection and not just probes in general.

**Comment by KSP-TaxiService** [comment]
Hi, may I have your output_log.txt per [guidelines](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports) please?

I tested it on CNC 1.5 and DMP 0.3.4 and the vessel control is no control when it is behind a moon, as shown below.
![1](https://user-images.githubusercontent.com/22871614/70329712-f98a0100-1876-11ea-9382-3c70bbe921e0.PNG)

**Comment by FrostBird347** [comment]
[KSP clean.log](https://github.com/KSP-TaxiService/CommNetConstellation/files/3934535/KSP.clean.log)

I also tried joining as another player (with the same save and commnet settings), but I still have control (it is locked, but the vessel control icon still shows)
![ksp4?](https://user-images.githubusercontent.com/39435218/70367079-b3b15500-18d7-11ea-9b2e-7f08684bc548.png)

**Comment by FrostBird347** [comment]
I just tried joining after removing all the quicksaves and persistant.sfs/loadme/save backups/etc.
I still have control.
![ksp5](https://user-images.githubusercontent.com/39435218/70367255-3d155700-18d9-11ea-8c8c-889d23f0f073.png)

**Comment by FrostBird347** [comment]
I made a copy of the server, removed the config folder and everything in the universe folder except for the ship in the screenshot above (in the vessels folder). I could still control it without a connection.

**Comment by KSP-TaxiService** [comment]
Hi @FrostBird347,

Thanks for your log. CNC at your end is 1.4, where there is the [new release 1.5](https://github.com/KSP-TaxiService/CommNetConstellation/releases/tag/v1.5) with the fix to the full control issue.

Please update CNC at your end.

**Comment by FrostBird347** [comment]
I thought I had 1.5...
![ksp999999](https://user-images.githubusercontent.com/39435218/70370069-b888ff80-18fd-11ea-80e1-db90685790af.png)
It works now, thanks!
