### ISSUE TITLE
Import/Export Constellations

### ISSUE THREAD

**Issue by dtoxic47** [KSP-TaxiService/CommNetConstellation#21]
Feature Request (if possible) to add Import/Export ability so we can export created constellations in say previous save and then import it into new save
Reason: saves a lot of typing when starting a new save :)

**Comment by KSP-TaxiService** [comment]
Hi, you could modify the default settings in `cnc_settings.cfg` in folder `GameData\CommNetConstellation`. These default settings will be used when a new save is started.

![image](https://user-images.githubusercontent.com/22871614/82215963-c467fb80-994a-11ea-839a-8ee1e986398c.png)

Is this what you look for?

**Comment by dtoxic47** [comment]
ok that will do it, so just to be clear, i can add my Constellation List, modify the frequency say (1,2,3,4 etc) then close it with brackets and that's that? Ground stations i only use the default so i dont need to modify that i guess

**Comment by KSP-TaxiService** [comment]
Yes, your understanding is correct.

Here's an example below for your reference.
```
Constellations
{
    Constellation
    {
        frequency = 0
        name = Public Broadcasting
        color = 0.649999976,0.649999976,0.649999976,1
    }
    Constellation
    {
        frequency = 1
        name = Channel 1
        color = 0.0196078438,0.678431392,0.980392158,1
    }
    Constellation
    {
        frequency = 2
        name = Channel 2
        color = 0.97647059,0.0235294122,0.447058827,1
    }
    Constellation
    {
        frequency = 3
        name = Channel 3
        color = 0.494117647,0.97647059,0.0352941193,1
    }
}
```

**Comment by dtoxic47** [comment]
great thx for the info
