### ISSUE TITLE
Cant Upgrade extra GroundStations.

### ISSUE THREAD

**Issue by WarGamerJustice** [KSP-TaxiService/CommNetConstellation#23]
Once you press edit on a groundstation that isnt KSC the window pops up to upgrade but it wont let you upgrade or close the window, the only thing you can do is alt+f4. It only happens on the dev builds.

**Comment by KSP-TaxiService** [comment]
Hi, I tried to reproduce your issue on the [latest dev build](https://github.com/KSP-TaxiService/CommNetConstellation/releases/tag/CommNetConstellation-1.5.3-116-develop) unsuccessfully.

Edit button opens the edit window, which can be closed. Upgrade button opens the upgrade window.

Kindly assist to re-test on the latest dev build and if the issue persists, give exact steps for the non-responsive window.

Thanks

**Comment by WarGamerJustice** [comment]
Hi, The edit button does seem to work but the upgrade button seems to get stuck on this menu
![20200529145600_1](https://user-images.githubusercontent.com/65814857/83224952-d143e500-a1bd-11ea-99b0-4cd5475131a8.jpg). Pressing the buttons doesnt do anything.

My steps are in the map menu I press the button to open the main menu in the toolbar> Press Ground stations> then press upgrade on any ground station then the menu pictured shows up but both buttons dont work so you have to Alt-f4.

My Mods are
MechJeb2
B9Partswitch
NearFutureLaunchVehicles
Community Resource Pack
DynamicBatteryStorage
NearFutureElectrical
NearFutureSolar
SCANsat
Tweakscale
Both DLC's
HyperEdit
TarsierSpaceTech
Kerbal Engineer

**Comment by KSP-TaxiService** [comment]
Whoops, I forgot to account for Sandbox and Science mode when implementing the upgrade funding.

Thanks for reporting the issue!

**Comment by WarGamerJustice** [comment]
Thanks! Keep up the great work! Love this mod!
