### ISSUE TITLE
Specified cast is invalid

### ISSUE THREAD

**Issue by timkoers** [KSP-TaxiService/CommNetConstellation#26]
When changing the frequency of a vessel's antenna, I get the message

![afbeelding](https://user-images.githubusercontent.com/4262725/86165122-294e6e00-bb13-11ea-8f02-834fd5b64563.png)

I don't think it is supposed to be there.

**Comment by KSP-TaxiService** [comment]
Hi,

Kindly assist to provide `output_log.txt` to investigate which third-party mod may cause this issue.

The issue is not reproducible on CNC 1.5.4 and KSP 1.10 alone.

**Comment by KSP-TaxiService** [comment]
Hi, a gentle reminder on this log provision.

**Comment by timkoers** [comment]
[KSP.log](https://github.com/KSP-TaxiService/CommNetConstellation/files/4981231/KSP.log)

This should be it I think!

**Comment by KSP-TaxiService** [comment]
Hi, thanks for your log.

I don't see any obvious mod that is causing the error. Normally, it would be CommNetManager which is known to be incompatible with CNC but it doesn't mess with CNC's own frequency update function.

I suspect something slipped into CommNet infrastructure and CNC could accidentally update that when updating the antenna frequency (successfully).

This error is not fatal and contained within CNC's protection sandbox (against bad user inputs).

If the error doesn't affect your vessels in any way, you can safely ignore it.

Thanks!

**Comment by timkoers** [comment]
Well, the mod is not working. None of my vessels are able to communicate with each other, either I'm doing something wrong, or it's the mods fault.
I don't have an active installation anymore, but I can set one up if you'd like. Will not be earlier than next thursday however

**Comment by KSP-TaxiService** [comment]
Based on what you describe, CNC is completely incompatible with CommNetManager to the point, where it is not even working.

You may want to uninstall CNC from your game if you like the other mod(s) with their dependency of CommNetManager.

**Comment by KSP-TaxiService** [comment]
Closed, with no further response received.
