### ISSUE TITLE
Tree List Collapsible Menu

### ISSUE THREAD

**Issue by dtoxic47** [KSP-TaxiService/CommNetConstellation#28]
Would you consider adding a Collapsible Tree/Menu Section (don't know how to call it) to group satellite's around certain bodies in their own group
So for an example 2 sats around Kerbin 2 around Moon would have two entries in the list Kerbin and Moon and once clicked on either one it would list the sats currently orbiting that body, like haystack does with vessels if you know the mod
reason being when there are a lot of satellites the scrolling becomes kind of cumbersome

**Comment by eberkain** [comment]
It would be nice to be able to collapse the planet and still have the moons open.

**Comment by KSP-TaxiService** [comment]
Thanks, this functionality is better now. Why don't you try out the [latest develop build](https://github.com/KSP-TaxiService/CommNetConstellation/releases/tag/CommNetConstellation-1.5.5-134-develop) and give some feedback?

**Comment by dtoxic47** [comment]
Thank you!
