### ISSUE TITLE
Commnet Manager NullRef

### ISSUE THREAD

**Issue by dtoxic47** [KSP-TaxiService/CommNetConstellation#29]
Commnet Manager port is throwing a few Nullrefs, this is from main menu to KSP-Center to VAB no Flight, KSP 1.12.3 Sandbox
i have not tested it on Career

i am using CommNetConstellation-1.5.7-cnm-157-commnet-manager-port-2 with the Commnet Manager from 156 since there is no commnet manager dll in the latest pre relase

[LOG 21:19:02.889] VesselModules: Found VesselModule of type AxisGroupsModule with order 999
[LOG 21:19:02.992] VesselModules: Found VesselModule of type CometVessel with order 999
[LOG 21:19:02.995] VesselModules: Found VesselModule of type SuspensionLoadBalancer with order 999
[LOG 21:19:02.996] VesselModules: Found VesselModule of type FlightIntegrator with order 0
[LOG 21:19:02.999] VesselModules: Found VesselModule of type CommNetVessel with order 999
[LOG 21:19:03.017] ModularCommNetVessel: CNMAPI: version 1.1.0.0 at E:\Games HDD\KSP_1.10\GameData\CommNetManager\CommNetManager.dll won the election against

[WRN 21:19:03.018] ModularCommNetVessel: OnAwake: Vessel is null.
[LOG 21:19:03.018] VesselModules: Found VesselModule of type ModularCommNetVessel with order 999
[EXC 21:19:03.023] NullReferenceException: Object reference not set to an instance of an object
	CommNetManager.ModularCommNetVessel.OnDestroy () (at <ac7eb2887b4d45609a22d3aa7ea53384>:0)
	UnityEngine.Object:DestroyImmediate(Object)
	<>c:<CompileModules>b__4_0(Type)
	LoadedAssembly:TypeOperation(Action`1)
	LoadedAssembyList:TypeOperation(Action`1)
	VesselModuleManager:CompileModules()
	<LoadObjects>d__90:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CreateDatabase>d__71:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	GameDatabase:StartLoad()
	<LoadSystems>d__11:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	LoadingScreen:Start()

and then this

[EXC 21:28:19.138] NullReferenceException: Object reference not set to an instance of an object
	CommNet.CommNetHome.CreateNode () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	CommNetManager.CNMHome.CreateNode () (at <ac7eb2887b4d45609a22d3aa7ea53384>:0)
	CommNet.CommNetHome.OnNetworkInitialized () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	CommNetManager.CNMHome.OnNetworkInitialized () (at <ac7eb2887b4d45609a22d3aa7ea53384>:0)
	CommNetManager.CNMHome.Start () (at <ac7eb2887b4d45609a22d3aa7ea53384>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[ERR 21:28:19.139] [CommNet Constellation] Error: CommNet Home 'Kerbin: Larkes' self-destructed due to body being null

[EXC 21:28:19.140] NullReferenceException: Object reference not set to an instance of an object
	CommNet.CommNetHome.CreateNode () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	CommNetManager.CNMHome.CreateNode () (at <ac7eb2887b4d45609a22d3aa7ea53384>:0)
	CommNet.CommNetHome.OnNetworkInitialized () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	CommNetManager.CNMHome.OnNetworkInitialized () (at <ac7eb2887b4d45609a22d3aa7ea53384>:0)
	CommNetManager.CNMHome.Start () (at <ac7eb2887b4d45609a22d3aa7ea53384>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[ERR 21:28:19.140] [CommNet Constellation] Error: CommNet Home 'Kerbin: Desert Launch Facility' self-destructed due to body being null

**Comment by KSP-TaxiService** [comment]
Hi, thanks for reporting the null reference spam. It is okay to take CNM folder from release 156 as I had not gotten around to copy it into auto-built release 157.

This is CNM startup behaviour and doesn't seem to cause any damaging issue. You can ignore this safely.
![normal](https://user-images.githubusercontent.com/22871614/152167815-3a31398c-c267-4373-a09f-35c0760c7b70.PNG)

This is CNC's failsafe when certain ground stations are not enabled i.e. 'Making History' DLC is not included ([see more details](https://wiki.kerbalspaceprogram.com/wiki/List_of_bases_on_Kerbin#Making_History_DLC_Launch_Site)). You can safely ignore.
![normal2](https://user-images.githubusercontent.com/22871614/152167824-b8dc026a-2d8b-4d90-8037-44f6a6a49bcb.PNG)

Thank you!

**Comment by dtoxic47** [comment]
Got it,thx for the info!
