### ISSUE TITLE
Ground Stations gone

### ISSUE THREAD

**Issue by Whovian41110** [KSP-TaxiService/CommNetConstellation#7]
The ground stations are no longer transmitting when they are enabled in the difficulties settings

**Comment by KSP-TaxiService** [comment]
Hi, I need more details on this. I can't make out what was going on from your initial post.

Before the setting option of extra ground stations was enabled, was there single ground station KSC? Did each of all stations have at least one frequency? 

In addition, please provide output_log.txt from KSP_x64_Data folder of your installation.

**Comment by Whovian41110** [comment]
[KSP.log](https://github.com/KSP-TaxiService/CommNetConstellation/files/1776423/KSP.log)
So basically I added this mod mid game in a game that had extra ground stations enabled. After this mod was installed the game failed to acknowledge that the extra ground stations exist at all. They don't show up in the CNC window or the map view as originators for comms lines

**Comment by KSP-TaxiService** [comment]
Thanks for your details.

Based on your log, KSP has the option of extra ground stations not enabled. Can you please double-check this option? You should be able to see multiple red circles on Kerbin (or start planet).

In addition, I notice you have other mods (Kopernicus, SigmaDimensions etc) that modify the planets/solar system. I am not sure if these mods affect the extra-station option.

I tested in stock KSP with CNC that the extra stations are shown up on Kerbin.
![image](https://user-images.githubusercontent.com/22871614/36936571-20b69f66-1f42-11e8-8f08-bc4ca1a409e1.png)

**Comment by Whovian41110** [comment]
My settings and save file agree that the extra ground stations are on. Additionally this problem only manifests when this mod is also installed

**Comment by Whovian41110** [comment]
oops

**Comment by KSP-TaxiService** [comment]
You are right. I don't understand how CNC does not see the extra stations on your sided since it reads KSP's public list of ground stations directly.

Do you know if any of your mods is also utilizing CommNet? It could be a mod conflict.

**Comment by Whovian41110** [comment]
Kerbalism, but that is fully turned off. I can't think of anything else

**Comment by KSP-TaxiService** [comment]
I downloaded it and disabled the signal feature but I can see the extra stations with CommNet and extra-option on. 

It is strange. I am going to try to reproduce this later.

**Comment by Whovian41110** [comment]
Hmm. Very strange

**Comment by Whovian41110** [comment]
Any updates?

**Comment by KSP-TaxiService** [comment]
Unfortunately, I am unable to reproduce this on two separate installations. My guess is the combination of your multiple mods, along with CNC, causes this weird bug.

Given this bug is not reproducible on KSP with CNC and few other mods, I am afraid I can't help with you on this :-/

**Comment by Whovian41110** [comment]
Any ideas as to what it might be? Would my .CKAN file help?

**Comment by KSP-TaxiService** [comment]
If possible, you can try this approach to find the mods responsible. Take out half of your mods and check if the extra stations are back. If not, put back and check the other half. Rinse and repeat this process.

You have quite lot of mods (and dependencies) on your installation though.

**Comment by KSP-TaxiService** [comment]
@Whovian41110 
Actually, I will take your .CKAN file to check. I misinterpreted it as full folder of files rather than installation-step file.

**Comment by Whovian41110** [comment]
here it is 
[1.3.1 Mods.ckan.zip](https://github.com/KSP-TaxiService/CommNetConstellation/files/1865910/1.3.1.Mods.ckan.zip)

**Comment by KSP-TaxiService** [comment]
Hi,

Sorry, I am unable to reproduce your bug of one ground station on your mods (with and without CNC). No matter what I changed the extra station setting, I see either Mission Control with the option disabled or all 7 stations with the option enabled.

Given this bug seems like a freak coincidence on your side, I am afraid I can't fix it here.
