### ISSUE TITLE
Freezes after science transmission

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-TaxiService/CommNetConstellation#9]
Referring to this:
https://forum.kerbalspaceprogram.com/index.php?/topic/108704-14x-dmagics-modlets-ksp-14-updates-3-25-2018/&do=findComment&comment=3398061

> If I had to bet it would be on some interaction between science relay and CommNetConstellation.  Probably something related to checking connectivity between vessels that would normally be connected in stock but aren't because they are on different networks in constellation. 

It happens on other science management mods, too.

It already happens when using stock transmission.

The "well-known" issue of a game freeze after each single science transmission.

Perhaps this is related to #8

**Comment by KSP-TaxiService** [comment]
Hi, 

Based on the new posts from DMagic and linuxgurugamer, the freezing/crash seems to come from somewhere else. It doesn't look like a performance shuttering/FPS drop, as expected in #8. I tested ScienceRelay 5.1 and CNC 1.2.1 on KSP 1.4.3 and didn't replicate the issue. 

I am going to leave this issue open for while to see if any new information on this problem gets posted.

**Comment by KSP-TaxiService** [comment]
Hmmm, I haven't see any new report on this freezing. I will close this thread for now.

It can be reopened should the issue be coming back again.
